### ISSUE TITLE
Why you know develop and design the whiteboard type software

### ISSUE THREAD

**Issue by ferren-qf** [SuhasDissa/SoftBoard#2]
Hi, I think your project are great !

I want develop whiteboard type software to use Compose Multiplatform, but I want konw the develop use the best practices;

Programming like data structure, code structure, and so on.

Like the title, Why you know develop and design the whiteboard type software? Where I will find source information;

Or tell me your development process, let me know if you have any thoughts on how to proceed with this;

Thank you for being patient with me ~;

**Comment by SuhasDissa** [comment]
Check this out https://codelabs.developers.google.com/?cat=Android&product=android

**Comment by ferren-qf** [comment]
thinks very much ~
